# Change these first
owner: fateme-mahmoodi # Your GitHub organization or username, where this repository lives
repo: fm-uptime # The name of this repository
user-agent: fateme-mahmoodi

sites:
  - name: fatememahmoodi.ir
    url: https://fatememahmoodi.ir
    expectedStatusCodes:
    - 200
    - 201
    - 302
    - 404
    assignees:
      - fateme-mahmoodi
      - AliAlmasi
  - name: al1almasi.ir
    url: https://al1almasi.ir
    assignees:
      - AliAlmasi

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  theme: dark
  baseUrl: /fm-uptime
  logoUrl: https://fatememahmoodi.ir/favicon-194x194.png
  name: fm-uptime
  metaTags:
    - name: "robots"
      content: "noindex"
  introTitle: "View [fm.ir](https://fatememahmoodi.ir) uptime status from here."
  introMessage: "Upptime is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: View Site
      href: https://fatememahmoodi.ir
    - title: Technical support
      href: https://al1almasi.ir

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
